In [1]:
import matplotlib.pyplot as plt
import numpy as np
import sympy as sym
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


En este cuaderno se calcularán numéricamente los campos producidos por una carga en movimiento en dos sistemas de referencia: el de la carga y el de un observador en reposo.

Primero buscamos el tensor de Faraday en el sistema de la carga. Podemos hacerlo directamente pues conocemos la forma del campo eléctrico producido por una carga puntual.

In [29]:
def Ex(x,y,z):
  return q*x/(np.sqrt(x**2+y**2+z**2)**3)

def Ey(x,y,z):
  return q*y/(np.sqrt(x**2+y**2+z**2)**3)

def Ez(x,y,z):
  return q*z/(np.sqrt(x**2+y**2+z**2)**3)
c=299792458
q=300
x=1
y=1
z=1
Fprima=np.array([[0, Ex(x,y,z)/c, Ey(x,y,z)/c, Ez(x,y,z)/c],[-Ex(x,y,z)/c, 0, 0, 0],[-Ey(x,y,z)/c, 0, 0, 0], [-Ez(x,y,z)/c, 0, 0, 0]], dtype=np.float128)
print(Fprima)

[[ 0.0000000e+00  1.9258332e-07  1.9258332e-07  1.9258332e-07]
 [-1.9258332e-07  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.9258332e-07  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.9258332e-07  0.0000000e+00  0.0000000e+00  0.0000000e+00]]


Ahora que tenemos el tensor de Faraday, podemos transformar al frame en reposo con una transformación de Lorentz.

In [26]:
vx = input('Ingrese la velocidad para el boost en x')
vy = input('Ingrese la velocidad para el boost en y')
vz = input('Ingrese la velocidad para el boost en z')
vx = float(vx)
betax=vx/c
vy = float(vy)
betay=vy/c
vz = float(vz)
betaz=vz/c
v2=vx**2+vy**2+vz**2
beta2=betax**2+betay**2+betaz**2
if v2>c**2:
  print('Este valor de velocidad no es posible, está por encima de c, los cálculos NO SON CORRECTOS')

Ingrese la velocidad para el boost en x300
Ingrese la velocidad para el boost en y0
Ingrese la velocidad para el boost en z0


Ahora se calcula directamente la T. de Lorentz con la forma general

In [27]:
Mgeneral=np.array([[gamma, -gamma*betax, -gamma*betay, -gamma*betaz],[-gamma*betax, 1+(gamma-1)*betax**2/beta2, (gamma-1)*betax*betay/beta2,(gamma-1)*betax*betaz/beta2],[-gamma*betay, (gamma-1)*betay*betax/beta2 ,1+(gamma-1)*betay**2/beta2, (gamma-1)*betay*betaz/beta2],[-gamma*betaz, (gamma-1)*betaz*betax/beta2, (gamma-1)*betay*betaz/beta2, 1+(gamma-1)*betaz**2/beta2]], dtype=np.float128)
print(Mgeneral)

[[ 1.09108945e+00 -1.09184480e-06 -0.00000000e+00 -0.00000000e+00]
 [-1.09184480e-06  1.09108945e+00  0.00000000e+00  0.00000000e+00]
 [-0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Con la T. de Lorentz calculada, podemos transformar al frame en el que nos interesa el movimiento.

In [28]:
F=Mgeneral.dot(Fprima.dot(Mgeneral))
print(F)

[[ 0.00000000e+00  7.64219524e-10  7.00418764e-10  7.00418764e-10]
 [-7.64219524e-10  0.00000000e+00 -7.00903653e-16 -7.00903653e-16]
 [-7.00418764e-10  7.00903653e-16  0.00000000e+00  0.00000000e+00]
 [-7.00418764e-10  7.00903653e-16  0.00000000e+00  0.00000000e+00]]
